name: py311_adv2
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.12.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h49ec1c0_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.2.0=py311h6b1f9c4_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli-python=1.2.0=py311h66f275b_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-cccl_linux-64=12.8.90=0
  - cuda-command-line-tools=12.8.1=0
  - cuda-compiler=12.8.1=0
  - cuda-crt-dev_linux-64=12.8.93=h06a4308_3
  - cuda-crt-tools=12.8.93=h06a4308_3
  - cuda-cudart=12.8.90=0
  - cuda-cudart-dev=12.8.90=0
  - cuda-cudart-dev_linux-64=12.8.90=0
  - cuda-cudart-static=12.8.90=0
  - cuda-cudart-static_linux-64=12.8.90=0
  - cuda-cudart_linux-64=12.8.90=0
  - cuda-cuobjdump=12.8.90=0
  - cuda-cupti=12.8.90=0
  - cuda-cupti-dev=12.8.90=0
  - cuda-cuxxfilt=12.8.90=0
  - cuda-driver-dev=12.8.90=0
  - cuda-driver-dev_linux-64=12.8.90=0
  - cuda-gdb=12.8.90=0
  - cuda-libraries=12.8.1=0
  - cuda-libraries-dev=12.8.1=0
  - cuda-nsight=12.8.90=0
  - cuda-nvcc=12.8.93=0
  - cuda-nvcc-dev_linux-64=12.8.93=he2511ca_3
  - cuda-nvcc-impl=12.8.93=hd1a145a_3
  - cuda-nvcc-tools=12.8.93=hbdd6827_3
  - cuda-nvcc_linux-64=12.8.93=0
  - cuda-nvdisasm=12.8.90=0
  - cuda-nvml-dev=12.8.90=0
  - cuda-nvprof=12.8.90=0
  - cuda-nvprune=12.8.90=0
  - cuda-nvrtc=12.8.93=0
  - cuda-nvrtc-dev=12.8.93=0
  - cuda-nvtx=12.8.90=0
  - cuda-nvvm-dev_linux-64=12.8.93=h06a4308_3
  - cuda-nvvm-impl=12.8.93=hbdd6827_3
  - cuda-nvvm-tools=12.8.93=hbdd6827_3
  - cuda-nvvp=12.8.93=0
  - cuda-opencl=12.8.90=0
  - cuda-opencl-dev=12.8.90=0
  - cuda-profiler-api=12.8.90=0
  - cuda-sanitizer-api=12.8.93=0
  - cuda-toolkit=12.8.1=0
  - cuda-tools=12.8.1=0
  - cuda-version=12.8=3
  - cuda-visual-tools=12.8.1=0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.19=py311hdb0dbe3_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=hecca717_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=14.3.0=h4943218_4
  - gcc_linux-64=14.3.0=hda73cce_12
  - gds-tools=1.13.1.3=0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=14.3.0=he634eba_4
  - gxx_linux-64=14.3.0=hca8765c_12
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=12.8.4.1=0
  - libcublas-dev=12.8.4.1=0
  - libcufft=11.3.3.83=0
  - libcufft-dev=11.3.3.83=0
  - libcufile=1.13.1.3=0
  - libcufile-dev=1.13.1.3=0
  - libcurand=10.3.9.90=0
  - libcurand-dev=10.3.9.90=0
  - libcusolver=11.7.3.90=0
  - libcusolver-dev=11.7.3.90=0
  - libcusparse=12.5.8.93=0
  - libcusparse-dev=12.5.8.93=0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=14.3.0=he7458c1_104
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libnpp=12.3.3.100=0
  - libnpp-dev=12.3.3.100=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.8.90=0
  - libnvfatbin-dev=12.8.90=0
  - libnvjitlink=12.8.93=1
  - libnvjitlink-dev=12.8.93=1
  - libnvjpeg=12.3.5.92=0
  - libnvjpeg-dev=12.3.5.92=0
  - libpng=1.6.50=h2ed474d_0
  - libsanitizer=14.3.0=hd4faa28_4
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=14.3.0=he7458c1_104
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nsight-compute=2025.1.1.2=0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py311h902ca64_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.28=h3108a97_1
  - terminado=0.18.1=pyhc90fa1f_1
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.4=py311h41d9c34_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - accelerate==1.12.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==6.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - apache-tvm-ffi==0.1.7
      - astor==0.8.1
      - av==16.0.1
      - bitsandbytes==0.49.1
      - blake3==1.0.8
      - blinker==1.9.0
      - cachetools==6.2.4
      - cbor2==5.8.0
      - cffi==2.0.0
      - click==8.3.1
      - cloudpickle==3.1.2
      - coloredlogs==15.0.1
      - compressed-tensors==0.12.2
      - contourpy==1.3.3
      - coverage==7.13.1
      - cryptography==46.0.3
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - depyf==0.20.0
      - diffusers==0.36.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - execnet==2.1.2
      - fastapi==0.128.0
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.8.0
      - fastar==0.8.0
      - fastrlock==0.8.3
      - ffmpy==1.0.0
      - filelock==3.20.1
      - flashinfer-python==0.5.3
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - gradio==6.2.0
      - gradio-client==2.0.2
      - groovy==0.1.2
      - helper-dev-utils==0.5.3
      - helper-plot-hangul==0.5.6
      - helper-streamlit-utils==0.1.0
      - hf-xet==1.2.0
      - httptools==0.7.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - ijson==3.4.0.post0
      - imageio==2.37.2
      - iniconfig==2.3.0
      - interegular==0.3.3
      - ipywidgets==8.1.8
      - jiter==0.12.0
      - jmespath==1.0.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lark==1.2.2
      - lazy-loader==0.4
      - llama-cpp-python==0.3.16
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mcp==1.25.0
      - mdurl==0.1.2
      - mistral-common==1.8.8
      - model-hosting-container-standards==0.1.12
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - narwhals==2.15.0
      - networkx==3.6.1
      - ninja==1.13.0
      - notebook==7.5.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.17.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.4
      - nvidia-ml-py==13.590.44
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - onnxruntime==1.23.2
      - openai==2.14.0
      - openai-harmony==0.0.8
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.5
      - outlines-core==0.2.11
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - peft==0.18.1
      - pillow==12.0.0
      - pluggy==1.6.0
      - pooch==1.8.2
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.11.0
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pydub==0.25.1
      - pyjwt==2.10.1
      - pymatting==1.1.14
      - pyparsing==3.3.1
      - pytest==8.4.2
      - pytest-asyncio==0.25.2
      - pytest-cov==7.0.0
      - pytest-html==4.1.1
      - pytest-metadata==3.1.1
      - pytest-timeout==2.4.0
      - pytest-xdist==3.8.0
      - python-dotenv==1.2.1
      - python-multipart==0.0.21
      - qwen-vl-utils==0.0.14
      - ray==2.53.0
      - regex==2025.11.3
      - rembg==2.0.69
      - rich==14.2.0
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scipy==1.16.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.48.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - smmap==5.0.2
      - spaces==0.46.0
      - sse-starlette==3.1.1
      - starlette==0.50.0
      - streamlit==1.52.2
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tifffile==2025.12.20
      - tiktoken==0.12.0
      - timm==1.0.22
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - transformers==4.57.5
      - triton==3.5.0
      - typer==0.21.0
      - typer-slim==0.21.1
      - typing-inspection==0.4.2
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - vllm==0.13.0
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - websockets==15.0.1
      - widgetsnbextension==4.0.15
      - xgrammar==0.1.27
      - yarl==1.22.0
prefix: /home/spai0433/miniconda3/envs/py311_adv2
