name: py311_ad
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2025.12.2=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libgomp=15.2.0=h4751f2c_7
  - tzdata=2025b=h04d1e81_0
  - _openmp_mutex=5.1=1_gnu
  - libgcc=15.2.0=h69a1729_7
  - keyutils=1.6.3=hb9d3cd8_0
  - libexpat=2.7.3=hecca717_0
  - libgcc-ng=15.2.0=h166f726_7
  - libnsl=2.0.1=hb9d3cd8_1
  - libstdcxx=15.2.0=h39759b7_7
  - openssl=3.6.0=h26f9b46_0
  - yaml=0.2.5=h280c20c_3
  - bzip2=1.0.8=h5eee18b_6
  - expat=2.7.3=hecca717_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libxcb=1.17.0=h9b100fa_0
  - readline=8.3=hc2a1206_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - krb5=1.21.3=h659f571_0
  - sqlite=3.51.0=h2a70700_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - tk=8.6.15=h54e0aa7_0
  - zeromq=4.3.5=h387f397_9
  - python=3.11.14=h6fa692b_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - lark=1.3.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - tomli=2.3.0=pyhcf101f3_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - zipp=3.23.0=pyhcf101f3_1
  - async-lru=2.0.5=pyh29332c3_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.2.0=py311h6b1f9c4_0
  - bleach=6.3.0=pyhcf101f3_0
  - brotli-python=1.2.0=py311h66f275b_1
  - cached-property=1.5.2=hd8ed1ab_1
  - debugpy=1.8.19=py311hdb0dbe3_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.0=py311haee01d2_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py311h902ca64_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tornado=6.5.4=py311h41d9c34_0
  - typing-extensions=4.15.0=h396c80c_0
  - anyio=4.12.0=pyhcf101f3_0
  - argon2-cffi-bindings=25.1.0=py311h49ec1c0_2
  - arrow=1.4.0=pyhcf101f3_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - ipython=9.8.0=pyh53cf698_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - referencing=0.37.0=pyhcf101f3_0
  - terminado=0.18.1=pyhc90fa1f_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - ipykernel=7.1.0=pyha191276_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - requests=2.32.5=pyhcf101f3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - jupyterlab=4.5.1=pyhd8ed1ab_0
  - nvidia-ml-py
prefix: /home/spai0433/miniconda3/envs/py311_ad
